# Generated by Django 5.2 on 2025-04-16 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='applicant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='applicant.applicantprofile'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='education',
            field=models.ManyToManyField(blank=True, to='applicant.education'),
        ),
        migrations.AddField(
            model_name='experience',
            name='applicant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='applicant.applicantprofile'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='experience',
            field=models.ManyToManyField(blank=True, to='applicant.experience'),
        ),
    ]
