# Generated by Django 5.2 on 2025-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='headline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='summary',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='applicant.skill'),
        ),
    ]
