services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dhaggitt
      POSTGRES_PASSWORD: donnie5524
      POSTGRES_DB: job_connect
    ports:
      - "8001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhaggitt -d job_connect"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8000:8000"
    links:
      - "db:database"