# Generated by Django 5.2 on 2025-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_skill_alter_applicantprofile_headline_and_more'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='applicant.skill'),
        ),
    ]
