# Generated by Django 5.2 on 2025-04-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_skill_alter_applicantprofile_headline_and_more'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='required_in_jobs', to='applicant.skill'),
        ),
    ]
